language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - mkdir $HOME/bin
  - curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.6.tgz
  - tar -zxvf mongodb-linux-x86_64-3.0.6.tgz
  - mkdir -p $HOME/bin/mongodb
  - cp -R -n mongodb-linux-x86_64-3.0.6/* $HOME/bin/mongodb
  - export PATH=$HOME/bin/mongodb/bin:$PATH
  - mongod --version
  - java -version
  - npm install -g bower
  - npm install
